let num1=Math.floor(Math.random()*100)+10;
console.log("Number 1 : "+num1);
let num2=Math.floor(Math.random()*100)+10;
console.log("Number 2 : "+num2);
let num3=Math.floor(Math.random()*100)+10;
console.log("Number 3 : "+num3);
let num4=Math.floor(Math.random()*100)+10;
console.log("Number 4 : "+num4);
let num5=Math.floor(Math.random()*100)+10;
console.log("Number 5 : "+num5);
let sum = num1 + num2 + num3 + num4 + num5;
let avg = sum/5;
console.log('Sum of Five Random Numbers = ' +sum);
console.log('Average of Five Random Numbers = ' +avg);